configuration:
  runtime: "concord-v2"
triggers:
  - github:
      version: 2
      useInitiator: true
      entryPoint: default
      conditions:
        type: ".*"
        githubRepo: ".*"
flows:
  default:
    - log: "yo, ${event}!"
